機能追加
Daiya199778/mokumoku pull request #2
Opened 2023-01-18 08:45 UTC by Daiya199778

お疲れ様です。

選択した課題：2
 「直近一年間で、2回以上もくもく会に参加してくれた人は利用者全体の1%のみ。
 もくもく会で気の合う仲間を見つけられなかったのではないか？」

上記の内容につきまして、実装を行いましたのでご確認のほどお願いします。
[rspec]
[![Image from Gyazo](https://i.gyazo.com/5a44139d218d8e7e36c1b195b7e5c2c6.png)](https://gyazo.com/5a44139d218d8e7e36c1b195b7e5c2c6)

2023-01-19 10:38 UTC, busitora requested changes
コメントしました！

2023-01-19 10:38 UTC, busitora commented on app/controllers/relationships_controller.rb
> +  def set_user
26行目と27行目に 改行いれましょうか!
(こちらは好みの問題ですが、空いていないことがほぼないです)

2023-01-19 10:38 UTC, busitora commented on app/controllers/users_controller.rb
> +
無駄な改行 削除お願いします

2023-01-19 10:38 UTC, busitora commented on app/decorators/relationship_decorator.rb
> +  delegate_all
使わないファイルはコミットしないようにしましょう
YAGNI

2023-01-19 10:38 UTC, busitora commented on app/models/user.rb
> +    relationship = self.relationships.find_by(follow_id: other_user.id)
early return 使ったほうが良いですね!

2023-01-19 10:38 UTC, busitora commented on app/views/events/show.html.erb
> +            <ul class="list-unstyled">
class 名の命名を 分かるように変更してください！

2023-01-19 10:38 UTC, busitora commented on app/views/events/show.html.erb
> +            </ul>
謎の空白 改行

2023-01-19 10:38 UTC, busitora commented on app/views/relationships/_follow_button.html.erb
> +<% unless current_user == user %>
unless と if で脳のメモリ使う可読性に欠けるので
if でまとめてワンライナーで書いてください！

2023-01-19 10:38 UTC, busitora commented on app/views/relationships/_follow_button.html.erb
> +    <%= form_with model: @relationship, url: relationship_path, method: :delete, local: true do |f| %>
パーシャルにインスタンス変数渡さないようにしてください！
```suggestion
    <%= form_with model: relationship, url: relationship_path, method: :delete, local: true do |f| %>
```

2023-01-19 23:00 UTC, Daiya199778 commented
ブシトラさん
お疲れ様です。

昨日は、お忙しい中ご確認頂きありがとうございます！
只今、変更事項の編集を行いましたので、commit致しました。

ご確認のほどよろしくお願い致します。

2023-01-20 02:02 UTC, Tsuchiya2 commented
1コメントに1コミットするようにしましょう。
GitHubに表示されている[079029e](https://github.com/Daiya199778/mokumoku/pull/2/commits/079029ed226698479168416d4291bc71768b9ba3)の部分をコピーして、どのコミットがどのコメントに対応しているかがパッと見て分かるようにするとレビュー側の負担を減らせて良いですよ。

2023-01-20 02:06 UTC, Tsuchiya2 reviewed
~~いくつか対応漏れがあったようなので、その部分に関してコメントしました。~~

↑送信に失敗していたようです。申し訳ございません🙇

2023-01-20 02:06 UTC, Tsuchiya2 commented on app/models/user.rb
> +    relationship = self.relationships.find_by(follow_id: other_user.id)
ここの指摘は対応されていますでしょうか？ご確認をお願いします。

2023-01-20 02:06 UTC, Tsuchiya2 commented on app/views/events/show.html.erb
> +            <ul class="list-unstyled">
ここの指摘は対応されていますでしょうか？ご確認をお願いします。

2023-01-21 04:01 UTC, masa-oh commented on app/controllers/relationships_controller.rb
> +  def set_user
079029 で修正しました。
↑のようにコメントしましょう。

2023-01-21 04:03 UTC, masa-oh commented on app/controllers/relationships_controller.rb
> +  def set_user
@Daiya199778 
修正されているのを確認しました。
↓のようにコメントしましょう。

079029e で修正しました。

2023-01-21 04:03 UTC, masa-oh commented on app/controllers/users_controller.rb
> +
@Daiya199778 
修正されているのを確認しました。
↓のようにコメントしましょう。

079029e で修正しました。

2023-01-21 04:03 UTC, masa-oh commented on app/decorators/relationship_decorator.rb
> +  delegate_all
@Daiya199778 
修正されているのを確認しました。
↓のようにコメントしましょう。

079029e で修正しました。

2023-01-21 04:05 UTC, masa-oh commented on app/models/user.rb
> +    relationship = self.relationships.find_by(follow_id: other_user.id)
修正方法が意図しているものと違うようです。
early return（早期returnとも言います）について調べてみてください。

2023-01-21 04:06 UTC, masa-oh commented on app/views/events/show.html.erb
> +            <ul class="list-unstyled">
修正されているのを確認しました。
↓のようにコメントしましょう。

079029e で修正しました。

2023-01-21 04:06 UTC, masa-oh commented on app/views/events/show.html.erb
> +            </ul>
修正されているのを確認しました。
↓のようにコメントしましょう。

079029e で修正しました。

2023-01-21 04:11 UTC, masa-oh commented on app/views/relationships/_follow_button.html.erb
> +    <%= form_with model: @relationship, url: relationship_path, method: :delete, local: true do |f| %>
単に`@`を外すだけだと、relationshipという名前が見つからなくてエラーになってはいないでしょうか？
partialを呼び出す側で、ローカル変数を渡してあげないといけないですよね。
また、同じファイルの別の部分でインスタンス変数を使っている箇所が直っていないようですので、ご確認ください。

2023-01-21 04:14 UTC, masa-oh commented
@Daiya199778 
指摘事項で対応できていない箇所がまだいくつかあるようです。
現状、どれが対応済みで、どれが未対応かということが、レビュイーにもレビュアーにもわかりづらくなっていると思います。
双方の負担を減らすため、修正時には、必ず以下の対応をお願いします。
- コミットを適切に分割する
- どの指摘事項に対応したか、コメントのツリーで返信する

2023-01-22 02:14 UTC, murata0705 commented
こちら修正済みですか？
修正完了した場合、RSpec 実行して通ってるか確認し、またキャプチャ貼ってみてください。

2023-01-28 08:01 UTC, merged