実装_再作成
Daiya199778/mokumoku pull request #3
Opened 2023-01-24 07:24 UTC by Daiya199778

講師様

お忙しいところ恐れ入ります。

vscode等に不具合があり編集ができない状態なってしまったため、再度作り直し致しました。
お手数をお掛け致しますが、ご確認のほどよろしくお願いします。

[課題]：2

[rspec]
[![Image from Gyazo](https://i.gyazo.com/8dcc0fc515d57965939ff6f1e1c4bdec.png)](https://gyazo.com/8dcc0fc515d57965939ff6f1e1c4bdec)

2023-01-24 12:22 UTC, enda1111 reviewed
コメントしました！

2023-01-24 12:22 UTC, enda1111 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
https://github.com/Daiya199778/mokumoku/pull/2/commits/5df537841dc9a0978178b04402f277ce683200be#r1081074633
こちらで判定していた処理を消してしまったのはなぜですか？

2023-01-24 12:22 UTC, enda1111 commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
find_byで見つからなかった場合にエラーになってしまいそうなので、何か対策した方がよいかなと思います。

2023-01-24 14:40 UTC, Daiya199778 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
コメントありがとうございます。

フォロー機能につき、User側のアソシエーションの記述を変更したため、併せてモデルのメソッドも変更いたしました。

2023-01-24 14:41 UTC, Daiya199778 commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
コメントありがとうございます。
コメント頂きました内容につきまして、ご教示頂きたい点がございます。

find_byで見つからなかった場合にエラー　＝＝「フォローしているユーザーが見つからない」
という認識になりますでしょうか？
上記の場合、他ユーザーをフォローしているユーザーが見当たらないということはあるのでしょうか？

2023-01-26 01:13 UTC, Tsuchiya2 commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
コード上ですが、`relationships.find_by(followed_id: user_id)`の部分で見つからなかった際に、その後にあるdestroyメソッドを実行するとエラーになるということだと思います。

find_byを使用した際にレコードが見つからなかった場合の返り値と、その返り値にdestroyメソッドが実行できるかを確認してみましょう。

2023-01-26 01:17 UTC, Tsuchiya2 commented
質問に回答しました。ご確認＆対応をお願いします。

また、1コメントに対して1コミットを心がけ、どのコメントに対してどのコミットで対応できているかを各コメントに記載するようにお願いします。（このPR上にあるコミットID [9cc573b](https://github.com/Daiya199778/mokumoku/pull/3/commits/9cc573b30a12ea1a5fed2696da451d8b60f8e6c2) をコピーして各コメントに貼り付けて分かるようにしましょう）

2023-01-26 04:12 UTC, Daiya199778 commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
お疲れ様です！

只今、フォロー解除機能の編集を行いました。
併せて、再度rspecの結果も添付いたします。
ご確認のほどお願いします。

f8cfb5b714649e55976bac0f6eea31a3870d9741

[rspec]
![image](https://user-images.githubusercontent.com/108708400/214756886-6d36b13f-1362-4aba-9446-125212480b17.png)


⭐️参考までにご教示いただきたいのですが、
この場合の書き方としまして、下記のように「ぼっち演算子」で記述することも可能になるのでしょうか？

def unfollow(user_id)
  relationships.find_by(followed_id: user_id)&.destroy　→（記述方法が間違えていたら申し訳ないです。。）
end

2023-01-26 04:15 UTC, Daiya199778 commented
お疲れ様です。

指摘いただきました箇所の編集を行いました。

ご確認のほどお願いします。

https://github.com/Daiya199778/mokumoku/pull/3#discussion_r1087344458

2023-01-26 10:42 UTC, busitora requested changes

2023-01-26 10:42 UTC, busitora commented on app/models/relationship.rb
> +  belongs_to :followed, class_name: "User"
following の方が一般的な気がしますね！
一度 フォロワー rails とかで調べてみてください！(直さなくてもいいです)

2023-01-26 10:42 UTC, busitora commented on app/models/user.rb
> +    relationship.destroy if relationship
```suggestion
   return if relationship.blank?
   relationship.destroy 
```
個人的にはこっち派(直さなくてもいいです)

2023-01-26 10:42 UTC, busitora commented on spec/factories/relationships.rb
> +    follower_id { 1 }
マジックナンバーは書かない対応おねがいします。

2023-01-26 10:42 UTC, busitora commented on spec/models/relationship_spec.rb
> +
不要であれば削除おねがいします。

2023-01-26 10:42 UTC, busitora commented on spec/rails_helper.rb
> +
無駄な空白

2023-01-26 10:52 UTC, Daiya199778 commented on app/models/relationship.rb
> +  belongs_to :followed, class_name: "User"
ブシトラさん。

コメントありがとうございます！
一度調べてみます！！

2023-01-26 10:53 UTC, Daiya199778 commented on app/models/user.rb
> +    relationship.destroy if relationship
ブシトラさん。

コメントありがとうございます！

参考になります！
ありがとうございます！

2023-01-26 10:58 UTC, Daiya199778 commented on spec/factories/relationships.rb
> +    follower_id { 1 }
ブシトラさん

コメントありがとうございます！

マジックナンバーの内容を調べてみたところ、
「可読性」「保守性」「脆弱性」の負の三要素を生む可能性があることを学びました。。。
記事でも、できれば使わない方が良いと書いてありましたので、削除致します！！

ご確認のほどお願い致します！

2023-01-26 11:26 UTC, Daiya199778 commented on spec/rails_helper.rb
> +
ブシトラさん

コメントありがとうございます！

謎の空白、削除致しました。

ご確認のほどお願いします！

2023-01-26 11:33 UTC, Daiya199778 commented on spec/models/relationship_spec.rb
> +
ブシトラさん

コメントありがとうございます！

使っていないファイルを消しそびれておりました。。。

[4225932](https://github.com/Daiya199778/mokumoku/pull/3/commits/42259323ebe8a763e20ae13f56355e692e17fb9f)

削除致しましたで、ご確認のほどお願いします！

2023-01-26 11:49 UTC, Daiya199778 commented
講師様

お疲れ様です。
お忙しいところ恐れ入ります。

[指摘コメント]
https://github.com/Daiya199778/mokumoku/pull/3#discussion_r1087688020
[修正コミット]
[4225932](https://github.com/Daiya199778/mokumoku/pull/3/commits/42259323ebe8a763e20ae13f56355e692e17fb9f)

[指摘コメント]
https://github.com/Daiya199778/mokumoku/pull/3#discussion_r1087728839
[修正コミット]
[4225932](https://github.com/Daiya199778/mokumoku/pull/3/commits/42259323ebe8a763e20ae13f56355e692e17fb9f)

[指摘コメント]
https://github.com/Daiya199778/mokumoku/pull/3#discussion_r1087721163
[修正コミット]
[3f37b24](https://github.com/Daiya199778/mokumoku/pull/3/commits/3f37b2430421146ca3cda66cdcd64af823119b7b)

講師様よりご指摘頂きました3か所の削除依頼につきまして、
修正しましたので、ご確認のほどお願い致します。

2023-01-26 12:03 UTC, busitora commented on app/models/user.rb
> +    relationship.destroy if relationship
early return で明示的に抜ける手法ですね
https://zenn.dev/media_engine/articles/early_return

2023-01-26 12:05 UTC, busitora requested changes
もう一点！よろしくおねがいします！
今の段階で マジックナンバー意識できているとgood なので、よろしくおねがいします！

2023-01-26 12:05 UTC, busitora commented on spec/factories/relationships.rb
> -    follower_id { 1 }
詳細伝えるべきでしたね。。factoryは残してほしいです！
association 等使い、 1 という 固定値を記載するのを避けてほしいです！

2023-01-26 12:42 UTC, Daiya199778 commented on spec/factories/relationships.rb
> -    follower_id { 1 }
ブシトラさん

お疲れ様です。

「１」という固定値を記載しない方法とは

factory :relationship, class: Relationship do
    follower_id { follower.id }
    followed_id { followed.id }
  end

上記のような記載で良いのでしょうか？

2023-01-26 13:03 UTC, Daiya199778 commented
ブシトラさん

お疲れ様です。

１か所の修正箇所につきまして、
再度修正いたしました。

[修正コメント]
https://github.com/Daiya199778/mokumoku/pull/3#discussion_r1087813141
[変更コミット]
[8fab52b](https://github.com/Daiya199778/mokumoku/pull/3/commits/8fab52b1864160473e8b9fee44c075663992f237)


ご確認のほどお願いします。

2023-01-28 01:47 UTC, murata0705 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
> フォロー機能につき、User側のアソシエーションの記述を変更したため、併せてモデルのメソッドも変更いたしました。

アソシエーションの記述を変更するとなぜ前回のコードと変わるのか詳細の説明もお願いします 🙏🏻

2023-01-28 01:47 UTC, murata0705 commented on app/models/relationship.rb
> +  belongs_to :followed, class_name: "User"
こちら調査後結論がでたらレビューリクエストお願いします

2023-01-28 02:42 UTC, Daiya199778 commented on app/models/relationship.rb
> +  belongs_to :followed, class_name: "User"
村田さん

お疲れ様です。
コメントありがとうございます！

「following」につきまして、
YouTubeで分かりやすく解説してくれている人がおりました。

following ：「あるユーザーをフォローしてくれる人」＝「フォローする人」になるため、
書き方としては「following」の方が一般的であることを学びました！

2023-01-28 02:44 UTC, Daiya199778 commented
お疲れ様です。

一件のコメントに返信致しましたので、
ご確認お願いします。

[コメント]
https://github.com/Daiya199778/mokumoku/pull/3#discussion_r1089603606

2023-01-28 02:51 UTC, murata0705 commented
https://github.com/Daiya199778/mokumoku/pull/3/files#r1085231081

こちらもお願いします 🙏🏻

2023-01-28 03:28 UTC, Daiya199778 commented
村田さん

1件のコメント対応漏れがありました。
申し訳ございませんでした。

[コメント]
https://github.com/Daiya199778/mokumoku/pull/3/files#r1089586988

ご確認のほどお願いします。

2023-01-28 03:41 UTC, murata0705 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
@Daiya199778 あれ、返信見えないです

2023-01-28 03:52 UTC, Daiya199778 commented
村田さん

一応、送れているみたいなのですが、
確認できますでしょうか？

[写真]
[![Image from Gyazo](https://i.gyazo.com/ee59e650a12cc21b93c74410c9698ce0.png)](https://gyazo.com/ee59e650a12cc21b93c74410c9698ce0)

今、自分のコメントをコピーしようとしたら、いつもは出るはずの「copy link」が出てこないです。。
これが原因なのでしょうか？？

2023-01-28 04:19 UTC, murata0705 commented
@Daiya199778 pending になってますね。右上の Review changes から comment を押すと更新されると思います。

2023-01-28 04:29 UTC, Daiya199778 reviewed
村田さん

恐らくこれで見れるかと思います。

一度、コメントの確認ができるかどうか、
確認のほどお願いします。

板谷

2023-01-28 04:29 UTC, Daiya199778 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
コメントが抜けており申し訳ございませんでした。

今回、モデルメソッドを別の記述方法で記載した背景としましては、
「フォロー機能」を作り直した際に、他の箇所も変更しようと思い、app/models/user.rb内の記述も変更しました。

ただ「アソシエーションの記述を変更したからモデルメソッドも変更する」という考え自体に誤りがありました。

・アソシエーション＝モデル同士の関係を明確にするためのもの。
・モデルメソッド＝モデル内にメソッドを記述することでコントローラに記述するコード数を軽減するためのもの。

上記の定義が正だと思います。
従って、アソシエーションを変更とモデルメソッドは別物であることが正しい認識だと思います。

2023-01-28 04:29 UTC, Daiya199778 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
村田さん

こちらでは正常に送られているようですが、見えないでしょうか？

[写真]
[![Image from Gyazo](https://i.gyazo.com/ee59e650a12cc21b93c74410c9698ce0.png)](https://gyazo.com/ee59e650a12cc21b93c74410c9698ce0)

こちらが送った内容になります。

2023-01-28 05:00 UTC, murata0705 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
> こちらで判定していた処理を消してしまったのはなぜですか？

あ、こちらで指摘されている「判定していた処理を消し」た理由を聞いておいたほうが良いかなと思いまして。

```ruby
return if self == other_user
```

とかですね

2023-01-28 06:03 UTC, Daiya199778 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
こちらはにつきましては、再度一から作り直した際に、
RSpecの要件にもある「他のユーザーをフォローできるし、フォロー解除することもできる。」について、
他ユーザー視点のフォロー機能等の記事を参考にしたところ、別の記述方法があり変更いたしました。

2023-01-28 06:06 UTC, Daiya199778 commented
村田さん

コメント致しましたので、
ご確認のほどお願い致します。

[コメント]
https://github.com/Daiya199778/mokumoku/pull/3#discussion_r1089652963

板谷

2023-01-28 06:42 UTC, murata0705 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
**1**
```ruby
def follow(user_id)
  return if self == user_id
  relationships.find_or_create_by(followed_id: user_id)
end
```

と

**2**
```ruby
def follow(user_id)
  relationships.create(followed_id: user_id)
end
```

だと、user_id が自身であった場合やすでに follow 済みの id が渡された時にメソッドの仕様がことなりますよね？そのため、どうしてメソッドの仕様を変えたのかを説明できると良いとおもいました。

とりあえず RSpec がとおっていて要求されている仕様は満たしているので良いですが、コードを変更されたら何を意図して変更したのかがレビューする側としては気になるので、そのあたり整理しておくと良いと思います。

2023-01-28 06:42 UTC, murata0705 commented
返信しましたが、参考にしてもらうのみで大丈夫です。
次の課題にすすみましょう 👍🏻

2023-01-28 06:46 UTC, Daiya199778 commented
村田さん

お忙しい中、コメント頂き、ありがとうございます。

引き続きよろしくお願いします！

2023-01-28 08:01 UTC, merged

2023-01-28 08:56 UTC, murata0705 commented on app/models/user.rb
> +    relationships.create(followed_id: user_id)
@Daiya199778 

> ⭐️いただいたコメントで恐縮ですが、
上記の記述にて、unfollowメソッドとfollowingメソッドのselfをつけなくても動作するのですが、
単純に、この場面では「省略できる」という認識で問題ないのでしょうか？

呼び出すときは省略できます。ただ assign するときなどは必要です。

```ruby
# name というカラムがあったとして

# ok
def set_name
  self.name = 'aaa'
end

# ng
def set_name
  name = 'aaa'
end
```